TEMPLATE:
    BACKEND: 'renderers/jinja_renderer.py',
    DIR:
        - '.'

PRODUCTION:
    LOADERS:
        - loaders/json_loader.py
        - loaders/yaml_loader.py
    MODULES:
        - 'loaders/loader.py'
        - 'loaders/lister.py'
        - 'loaders/extractor.py'
        - 'transformers/filename_transformer.py'
        - 'transformers/meta_functions.py'
        - 'transformers/data_transformer.py'
        - 'transformers/wrapper.py'
        - 'filters/selection_functions.py']
